apiVersion: apps/v1
kind: Deployment
metadata:
  name: nflow-generator
  labels:
    app: nflow-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nflow-generator
  template:
    metadata:
      labels:
        app: nflow-generator
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - /nflow-generator -t <collector_ip> -p <collector_port>
          image: quay.io/netobserv/nflow-generator:main
          imagePullPolicy: IfNotPresent
          name: nflow-generator
          resources:
            limits:
              memory: 512Mi
              cpu: "1"